# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JE
version:      0.019
version_from: lib/JE.pm
installdirs:  site
requires:
    Encode:                        0
    Exporter:                      5.57
    List::Util:                    0
    Memoize:                       0
    Scalar::Util:                  1.08
    Test::More:                    0
    Tie::RefHash::Weak:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
