--- #YAML:1.0
name:                JE
version:             0.020
abstract:            Pure-Perl ECMAScript (JavaScript) Engine
license:             ~
author:              
    - Father Chrysostomos <sprout @ cpan . org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Encode:                        2.02
    Exporter:                      5.57
    List::Util:                    0
    Memoize:                       0
    Scalar::Util:                  1.1
    strict:                        0
    Test::More:                    0
    Time::Local:                   0
    Time::Zone:                    0
    utf8:                          0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
